FitChildPanel/Controllers/OneriController.cs
using FitChildPanel.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FitChildPanel.Controllers
{
    [Authorize]
    public class OneriController : Controller
    {
        DBFITCHILDEntities db = new DBFITCHILDEntities();
        // GET: Oneri
        public ActionResult Index()
        {
            var oneriler = db.TBLONERI.ToList();
            return View(oneriler);
        }

        public ActionResult IslemGetir(int id)
        {
            var gelenVeri = db.TBLONERI.Find(id);
            return View("IslemGetir", gelenVeri);
        }

        public ActionResult IslemGuncelle(TBLONERI gelenOneri)
        {
            if (!ModelState.IsValid)
            {
                TempData.Add("oneriData", " güncelleme başarısız. Model geçersiz.");
                return View("IslemGetir");
            }
            gelenOneri.OneriEklenmeTarih = DateTime.Now;
            db.Entry(gelenOneri).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            TempData.Add("oneriData", " başarıyla güncellendi. ID: " + gelenOneri.ID);
            return RedirectToAction("Index");
        }

        public ActionResult IslemSil(int id)
        {

            var gelenVeri = db.TBLONERI.Find(id);
            db.TBLONERI.Remove(gelenVeri);
            db.SaveChanges();
            TempData.Add("oneriData", " başarıyla silindi. ID: " + id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult IslemEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult IslemEkle(TBLONERI eklenecekOneri)
        {
            if (!ModelState.IsValid)
            {
                TempData.Add("ekleOneriData", " ekleme başarısız. Model geçersiz.");
                return View("IslemEkle");
            }

            db.TBLONERI.Add(eklenecekOneri);
            eklenecekOneri.OneriEklenmeTarih = DateTime.Now;
            db.SaveChanges();
            TempData.Add("ekleOneriData", " başarıyla eklendi. ID: " + eklenecekOneri.ID);
            return View("IslemEkle");
        }
    }
}

FitChildPanel/Views/Oneri/Index.cshtml
@using FitChildPanel.Models.Entity
@model List<TBLONERI>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Öneriler</h2>
<hr />
@Html.ActionLink("Yeni Öneri", "IslemEkle", null, new { @class = "btn btn-dark" })
<br />
<br />
@if (TempData["oneriData"] != null)
{
    <div class="alert alert-success alert-dark">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Öneri </strong> @TempData["oneriData"]
    </div>
}
<br />

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Resim</th>
            <th>Ad</th>
            <th>Fayda</th>
            <th>Tavsiye</th>
            <th>Çalıştırdığı Bölge</th>
            <th>Eklenme Tarih</th>
            <th>Güncelle</th>
            <th>Sil</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var oneri in Model)
        {
        <tr>
            <td>@oneri.ID</td>
            <td>
                <img class="img-fluid" src="@oneri.OneriResim" alt="" />
            </td>
            <td>@oneri.OneriAdi</td>
            <td>@oneri.OneriFayda</td>
            <td>@oneri.OneriTavsiye</td>
            <td>@oneri.OneriCalisanBolge</td>
            <td>@Convert.ToDateTime(oneri.OneriEklenmeTarih).ToString("dd/MMM/yyyy")</td>
            <td><a href="/Oneri/IslemGetir/@oneri.ID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Oneri/IslemSil/@oneri.ID" class="btn btn-danger" onclick="return confirm('Silmek istiyor musunuz?')">Sil</a></td>
        </tr>
        }
    </tbody>
</table>

FitChildPanel/Views/Oneri/IslemEkle.cshtml
@model FitChildPanel.Models.Entity.TBLONERI
@{
    ViewBag.Title = "IslemEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Egzersiz Ekle</h2>
<hr />
@if (TempData["ekleOneriData"] != null)
{
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Öneri </strong> @TempData["ekleOneriData"]
    </div>
}
<br />
<form class="form-group was-validated" method="post">
    <div>
        <div class="form-group">
            @Html.Label("İşlem Tarihi:")
            @Html.Label(DateTime.Now.ToLongDateString())
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.OneriAdi)
            @Html.TextBoxFor(k => k.OneriAdi, new { @class = "form-control", placeholder = "Öneri Adı", required = "required" })
           
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.OneriFayda)
            @Html.TextAreaFor(k => k.OneriFayda, new { @class = "form-control", placeholder = "Öneri Fayda", required = "required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.OneriTavsiye)
            @Html.TextAreaFor(k => k.OneriTavsiye, new { @class = "form-control", placeholder = "Öneri Tavsiye", required = "required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.OneriCalisanBolge)
            @Html.TextAreaFor(k => k.OneriCalisanBolge, new { @class = "form-control", placeholder = "Öneri Çalışan Bölge", required = "required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.OneriResim)
            @Html.TextBoxFor(k => k.OneriResim, new { @class = "form-control", placeholder = "Öneri Resim", required = "required" })
        </div>
        <div>
            <button type="submit" class="btn btn-success">Kaydet</button>
        </div>
    </div>

</form>

FitChildPanel/Views/Oneri/IslemGetir.cshtml
@model FitChildPanel.Models.Entity.TBLONERI
@{
    ViewBag.Title = "IslemGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("IslemGuncelle", "Oneri", FormMethod.Post, new { @class = "was-validated" }))
{
    @Html.AntiForgeryToken();

    <div style="margin-bottom:15px;">
        <div class="form-group">
            @Html.Label("İşlem Tarihi:")
            @Html.Label(DateTime.Now.ToLongDateString())
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.OneriAdi)
            @Html.TextBoxFor(k => k.OneriAdi, new { @class = "form-control", placeholder = "Öneri Adı", required = "required" })

        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.OneriFayda)
            @Html.TextAreaFor(k => k.OneriFayda, new { @class = "form-control", placeholder = "Öneri Fayda", required = "required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.OneriTavsiye)
            @Html.TextAreaFor(k => k.OneriTavsiye, new { @class = "form-control", placeholder = "Öneri Tavsiye", required = "required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.OneriCalisanBolge)
            @Html.TextAreaFor(k => k.OneriCalisanBolge, new { @class = "form-control", placeholder = "Öneri Çalışan Bölge", required = "required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.OneriResim)
            @Html.TextBoxFor(k => k.OneriResim, new { @class = "form-control", placeholder = "Öneri Resim", required = "required" })
        </div>

    </div>

    <div>
        <button type="submit" class="btn btn-success">Güncelle</button>
    </div>
    @Html.HiddenFor(y => y.ID)
}