FitChildPanel/Controllers/EgzersizController.cs
using FitChildPanel.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FitChildPanel.Controllers
{
    [Authorize]
    public class EgzersizController : Controller
    {
        DBFITCHILDEntities db = new DBFITCHILDEntities();
        // GET: Egzersiz
        public ActionResult Index()
        {
            var egzersizler = db.TBLEGZERSIZ.ToList();
            return View(egzersizler);
        }

        public ActionResult IslemGetir(int id)
        {
            var gelenVeri = db.TBLEGZERSIZ.Find(id);
            return View("IslemGetir", gelenVeri);
        }

        public ActionResult IslemGuncelle(TBLEGZERSIZ gelenEgzersiz)
        {
            if (!ModelState.IsValid)
            {
                TempData.Add("egzersizData", " güncelleme başarısız. Model geçersiz.");
                return View("IslemGetir");
            }
            db.Entry(gelenEgzersiz).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            TempData.Add("egzersizData", " başarıyla güncellendi. ID: " + gelenEgzersiz.ID);
            return RedirectToAction("Index");
        }

        public ActionResult IslemSil(int id)
        {

            var gelenVeri = db.TBLEGZERSIZ.Find(id);
            db.TBLEGZERSIZ.Remove(gelenVeri);
            db.SaveChanges();
            TempData.Add("egzersizData", " başarıyla silindi. ID: " + id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult IslemEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult IslemEkle(TBLEGZERSIZ eklenecekEgzersiz)
        {
            if (!ModelState.IsValid)
            {
                TempData.Add("ekleData", " ekleme başarısız. Model geçersiz.");
                return View("IslemEkle");
            }
            db.TBLEGZERSIZ.Add(eklenecekEgzersiz);
            db.SaveChanges();
            TempData.Add("ekleData"," başarıyla eklendi. ID: "+ eklenecekEgzersiz.ID);
            return View("IslemEkle");
        }
    }
}

FitChildPanel/Views/Egzersiz/Index.cshtml
@using FitChildPanel.Models.Entity
@model List<TBLEGZERSIZ>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Egzersizler</h2>
<hr />
@Html.ActionLink("Yeni Egzersiz", "IslemEkle", null, new { @class = "btn btn-dark" })
<br />
<br />
@if (TempData["egzersizData"] != null)
{
<div class="alert alert-success alert-dark">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Egzersiz </strong> @TempData["egzersizData"]
</div>
}
<br />

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Resim</th>
            <th>Ad</th>
            <th>Yapılışı</th>
            <th>Fayda</th>
            <th>Seviye</th>
            <th>Güncelle</th>
            <th>Sil</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var egzersiz in Model)
        {
            <tr>
                <td>@egzersiz.ID</td>
                <td>
                    <img class="img-fluid" src="@egzersiz.EgzersizResim" alt="" />
                </td>
                <td>@egzersiz.EgzersizAdi</td>
                <td>@egzersiz.EgzersizYapilisi</td>
                <td>@egzersiz.EgzersizFayda</td>
                <td>@egzersiz.EgzersizSeviye</td>
                <td><a href="/Egzersiz/IslemGetir/@egzersiz.ID" class="btn btn-warning">Güncelle</a></td>
                <td><a href="/Egzersiz/IslemSil/@egzersiz.ID" class="btn btn-danger" onclick="return confirm('Silmek istiyor musunuz?')">Sil</a></td>
            </tr>
        }
    </tbody>
</table>

FitChildPanel/Views/Egzersiz/IslemEkle.cshtml
@model FitChildPanel.Models.Entity.TBLEGZERSIZ
@{
    ViewBag.Title = "IslemEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Egzersiz Ekle</h2>
<hr />
@if (TempData["ekleData"] != null)
{
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Egzersiz </strong> @TempData["ekleData"]
    </div>
}
<br />
<form class="form-group was-validated" method="post">
    <div>
        <div class="form-group">
            @Html.LabelFor(k => k.EgzersizAdi)
            @Html.TextBoxFor(k => k.EgzersizAdi, new { @class = "form-control", placeholder = "Egzersiz Adı", required = "required" })
            @*@Html.ValidationMessageFor(k => k.AD)*@
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.EgzersizYapilisi)
            @Html.TextAreaFor(k => k.EgzersizYapilisi, new { @class = "form-control", placeholder = "Egzersiz Yapılışı", required = "required", style = "height:200px" })
            @*@Html.ValidationMessageFor(k => k.AD)*@
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.EgzersizFayda)
            @Html.TextBoxFor(k => k.EgzersizFayda, new { @class = "form-control", placeholder = "Egzersiz Fayda", required = "required" })
            @*@Html.ValidationMessageFor(k => k.AD)*@
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.EgzersizSeviye)
            @Html.TextBoxFor(k => k.EgzersizSeviye, new { @class = "form-control", placeholder = "Egzersiz Seviye", required = "required" })
            @*@Html.ValidationMessageFor(k => k.AD)*@
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.EgzersizResim)
            @Html.TextBoxFor(k => k.EgzersizResim, new { @class = "form-control", placeholder = "Egzersiz Resim", required = "required" })
            @*@Html.ValidationMessageFor(k => k.AD)*@
        </div>
        <div>
            <button type="submit" class="btn btn-success">Kaydet</button>
        </div>
    </div>

</form>

FitChildPanel/Views/Egzersiz/IslemGetir.cshtml
@model FitChildPanel.Models.Entity.TBLEGZERSIZ
@{
    ViewBag.Title = "IslemGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("IslemGuncelle", "Egzersiz", FormMethod.Post, new { @class = "was-validated" }))
{
    @Html.AntiForgeryToken();

    <div style="margin-bottom:15px;">
        <div class="form-group">
            @Html.LabelFor(k => k.EgzersizAdi)
            @Html.TextBoxFor(k => k.EgzersizAdi, new { @class = "form-control", placeholder = "Egzersiz Adı", required = "required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.EgzersizYapilisi)
            @Html.TextAreaFor(k => k.EgzersizYapilisi, new { @class = "form-control", placeholder = "Egzersiz Yapılışı", required = "required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.EgzersizFayda)
            @Html.TextBoxFor(k => k.EgzersizFayda, new { @class = "form-control", placeholder = "Egzersiz Fayda", required = "required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.EgzersizSeviye)
            @Html.TextBoxFor(k => k.EgzersizSeviye, new { @class = "form-control", placeholder = "Egzersiz Seviye", required = "required" })
        </div>
        <div class="form-group">
            @Html.LabelFor(k => k.EgzersizResim)
            @Html.TextBoxFor(k => k.EgzersizResim, new { @class = "form-control", placeholder = "Egzersiz Resim", required = "required" })
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-success">Güncelle</button>
    </div>
    @Html.HiddenFor(y => y.ID)
}